spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-manager;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
#        default_batch_fetch_size: 100

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug